variables:
  SITE_FOLDER: '/home/devsi/peertube-mass-upload-main'

stages: # List of stages for jobs, and their order of execution
  - build
  - deploy

default: # On déclare ici les directives qui seront utilisés par défaut sur tous les jobs
  tags:
    - toolbox # On utilise un ou des runner qui possède ces tags (si aucun autre tag est déclaré dans le job)

before_script:
  - sed -i s/###mdpApi###/$MDP_API/ settings.yaml
  - sed -i s/###mdpDbVal###/$MDP_DB_VAL/ settings.yaml
  - sed -i s/###ipVal###/$IP_VAL/ settings.yaml
  - sed -i s/###mdpDbProd###/$MDP_DB_PROD/ settings.yaml
  - sed -i s/###ipProd###/$IP_PROD/ settings.yaml
  # --- Configuration SSH ---
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$PRIVATE_KEY")

build-npm: # compilation des css, js
  stage: build
  image: node:20-alpine
  before_script:
    - ''
  script:
    - npm install
  cache:
    key: ${CI_COMMIT_REF_SLUG}-npm
    paths:
      - node_modules/

.script_template:
  script:
    - rsync -avz --no-perms --exclude-from=exclude-rsync.txt -e "ssh" --checksum . devsi@$HOST:$SITE_FOLDER

# --- PROD ---
deploy-prod:
  stage: deploy
  only:
    - main
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ./
    policy: pull
  environment:
    name: production
  variables:
    HOST: rc-prod-cdn-03
  when: manual
  extends: .script_template
